# Generated by Django 5.2.16 on 2026-08-18 06:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('1', 'Shift 1'), ('2', 'Shift 2'), ('3', 'Shift 3')], max_length=1)),
                ('accountant', models.CharField(blank=True, max_length=200)),
                ('reference_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('staff_discount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('petty_cash', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cash_counts', models.JSONField(blank=True, default=dict)),
                ('cash_counts_aed', models.JSONField(blank=True, default=dict)),
                ('aed_exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1020'), max_digits=6)),
                ('cash_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('visa_entries', models.JSONField(blank=True, default=list)),
                ('visa_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('delivery_data', models.JSONField(blank=True, default=dict)),
                ('delivery_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('delivery_attachment_talabat', models.FileField(blank=True, null=True, upload_to='delivery_attachments/%Y/%m/')),
                ('delivery_attachment_tmdone', models.FileField(blank=True, null=True, upload_to='delivery_attachments/%Y/%m/')),
                ('delivery_attachment_khedmah', models.FileField(blank=True, null=True, upload_to='delivery_attachments/%Y/%m/')),
                ('delivery_attachment_callcenter', models.FileField(blank=True, null=True, upload_to='delivery_attachments/%Y/%m/')),
                ('actual_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('expected_foodics', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_entries', to='salesapp.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectorHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.CharField(blank=True, max_length=200)),
                ('cash_counts', models.JSONField(blank=True, default=dict)),
                ('cash_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('visa_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('delivery_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('actual_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('diff_from_waiter', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('diff_from_expected', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('recounted_at', models.DateTimeField(auto_now=True)),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to='salesapp.shiftentry')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'Waiter / Branch Accountant'), ('collector', 'Collector'), ('audit', 'Audit'), ('admin', 'Admin'), ('it', 'IT (Full Access)')], max_length=20)),
                ('head_cashier_name', models.CharField(blank=True, max_length=200)),
                ('punch_id', models.CharField(blank=True, max_length=50)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='salesapp.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisaMachineFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='visa_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_files', to='salesapp.shiftentry')),
            ],
        ),
    ]
