# Generated by Django 5.2.16 on 2026-08-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftentry',
            name='audit_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
