# Generated by Django 5.2.16 on 2026-08-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_shiftentry_audit_notes_shiftentry_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftentry',
            name='is_audited',
            field=models.BooleanField(default=False),
        ),
    ]
