# Generated by Django 5.2.16 on 2026-09-09 04:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0003_shiftentry_is_audited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftentry',
            name='aed_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=6),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('user_created', 'User Created'), ('user_edited', 'User Edited'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('account_unlocked', 'Account Unlocked'), ('branch_created', 'Branch Created'), ('branch_edited', 'Branch Edited'), ('branch_deleted', 'Branch Deleted'), ('branch_activated', 'Branch Activated'), ('branch_deactivated', 'Branch Deactivated'), ('entry_edited', 'Shift Entry Edited'), ('entry_archived', 'Shift Entry Archived'), ('entry_unarchived', 'Shift Entry Unarchived'), ('handover_saved', 'Collector Handover Saved'), ('entry_audited', 'Shift Entry Audited')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
