# Generated by Django 5.2.16 on 2026-09-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_alter_shiftentry_aed_exchange_rate_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftentry',
            name='cash_cancel_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='cash_cancel_attachment',
            field=models.FileField(blank=True, null=True, upload_to='cancel_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='delivery_cancel_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='delivery_cancel_attachment',
            field=models.FileField(blank=True, null=True, upload_to='cancel_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='delivery_cancel_source',
            field=models.CharField(blank=True, choices=[('talabat', 'Talabat'), ('tmdone', 'TM Done'), ('khedmah', 'Khedmah'), ('callcenter', 'Call Center')], max_length=20),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='notes_attachment',
            field=models.FileField(blank=True, null=True, upload_to='notes_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='staff_discount_attachment',
            field=models.FileField(blank=True, null=True, upload_to='discount_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='visa_cancel_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='visa_cancel_attachment',
            field=models.FileField(blank=True, null=True, upload_to='cancel_attachments/%Y/%m/'),
        ),
    ]
